# This is a basic workflow to help you get started with Actions

name: add_contributor

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches-ignore:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    # 팀원 자동 추가 액션
    - name: Contribute List
      uses: akhilmhdh/contributors-readme-action@v1.1
      env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      with:
          header: Teammates  
