name: update_md_title

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Configure pip caching
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/py-package.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Update README
        run: |-
          python update_readme.py
          cat README.md
      - name: commit and push if README changed 
        run: |-
          git config --local user.email "asdka4618@gmail.com"
          git config --local user.name "snowjang24"
          git add README.md && git commit -m "Updated README"
          git push origin HEAD:master
