name: update_md_title

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Configure pip caching
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/py-package.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Update README
        run: |-
          python update_readme.py
          cat README.md
      - name: Commit files
        run: |
          git config --local user.email "asdka4618@gmail.com"
          git config --local user.name "snowjang24"
          git add README.md
          git commit -m "Add changes"
          git push
